apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-health
  namespace: sim
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Health Check</title></head>
    <body><h1>OK</h1></body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-health
  namespace: sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-health
  template:
    metadata:
      labels:
        app: simple-health
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: simple-health
---
apiVersion: v1
kind: Service
metadata:
  name: simple-health
  namespace: sim
spec:
  selector:
    app: simple-health
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

